version: "3.9"
services:
  server:
    image: messaging_app:latest
    build: .
    ports:
      - "8000:80"
      - "8080:443"
    container_name: messaging_app
    environment:
      DB_CONNECTION: "Server=db;Database=MessagingAppFullStack;Trusted_Connection=True;MultipleActiveResultSets=true;User Id=SA;Password=Password123;Integrated Security=false"
      ASPNETCORE_URLS: "https://+443;http://+80"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_Kestrel__Certificates__Default__Password: "TestPass123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
    ports:
      - "1433:1433"